server:
  port: ":8080"
  mode: "debug"
  node_id: 1 # Snowflake Node ID (0-1023)

database:
  dsn: "root:root@tcp(127.0.0.1:3306)/shop?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

elasticsearch:
  addresses: 
    - "http://localhost:9200"
  username: ""
  password: ""

logger:
  level: "debug"
